### PR TITLE
Volume works, compiler warnings, newlib compilation

### PR DESCRIPTION
**Pull request by pwarren**
Hi Michael, my PSDR arrived on Thursday thanks :)

This PR adds changes to allow compilation on linux with newlib, fixes some of the easier compiler warnings from main.c and makes the volume menu item report the current AF gain setting * 10.

hope it's of use.

### CODE REVIEW

**Comment by pwarren** [comment]
And in that one I tardown the peripheral's power before calling the StandBy function. Next step I'll work out how to scan for input changes while in this mode!

**Comment by MichaelRColton** [comment]
AWESOME!

Give me a day or two to get these tested and merged back in. (I'm still a
little unskilled at some git operations)

You are my hero!

Your name sounds familiar (maybe because I've looked at the backer lists so
many times?) are you one of the people that built their own PSDR2s back
before it was on kickstarter?

Either way, thanks for your your work on this!

-Michael

**Comment by pwarren** [comment]
Heh no worries, I'm concerned the newlib change might prevent builds with other toolchains (like on windows) but it's an easy revert.

I'm also not 100% on git and github. Had to delete my old fork, and re-fork to get the new branches, which I then worked off, but got there in the end!

You might recognise the name because I paid extra to have my extreme kit upgraded to a non-soldering one, and I did the linux build instructions a while ago. 

I've also updated the wiki with linux build instructions and left a comment on kickstarter :)

**Comment by fstkmaro** [comment]
All, I hope all is well. Thanks for the continued work. Can this kit be acquired anymore? If so, where?

Thanks.

Sent from my iPhone

On Jan 3, 2017, at 1:19 AM, Paul Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Heh no worries, I'm concerned the newlib change might prevent builds with other toolchains (like on windows) but it's an easy revert.

I'm also not 100% on git and github. Had to delete my old fork, and re-fork to get the new branches, which I then worked off, but got there in the end!

You might recognise the name because I paid extra to have my extreme kit upgraded to a non-soldering one, and I did the linux build instructions a while ago.

I've also updated the wiki with linux build instructions and left a comment on kickstarter :)

-

**Comment by pwarren** [comment]
in: 1381f544d076de45f68b465aa66a190966a1f321 looks like I wiped the .gitignore, apologies!

@fstkmaro I've no Idea, @MichaelRColton would probably know, seeing as it's his project!

**Comment by fstkmaro** [comment]
thanks Paul



________________________________

**Comment by MichaelRColton** [comment]
Hi fstkmaro,

I'm still working out the details for building more of these. I can put you
on a list of people to contact if more become available, if you'd like.

**Pull request merged**
